name: Create new release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master # Use master version
      - name: Install dependency
        run: sudo apt-get update && sudo apt-get install -y fuse libfuse2 libgl1

      - name: Make Calibre AppDir
        run: |
          set -x
          version=$(grep -o "Calibre:.*" README.md | cut -d ' ' -f2)
          echo "Calibre version: $version"

          mkdir -p build/calibre.AppDir/

          cat > build/calibre.AppDir/calibre.desktop << 'EOF'
          [Desktop Entry]
          Type=Application
          Name=Calibre
          GenericName=E-book library management
          Comment=E-book library management: Convert, view, share, catalogue all your e-books
          Exec=calibre %F
          Icon=calibre
          MimeType=application/x-mobipocket-ebook;application/epub+zip;x-content/ebook-reader
          Categories=Office;Graphics;Viewer;
          X-GNOME-UsesNotifications=true
          Actions=Ebook-editor;Ebook-viewer;LRF-viewer;
          
          [Desktop Action Ebook-editor]
          Name=Ebook editor
          Exec=ebook-edit %f
          
          [Desktop Action Ebook-viewer]
          Name=Ebook viewer
          Exec=ebook-viewer %f
          
          [Desktop Action LRF-viewer]
          Name=LRF viewer
          Exec=lrfviewer %f

          EOF

          chmod +x build/calibre.AppDir/calibre.desktop

          curl --location -o build/calibre.AppDir/AppRun https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64
          chmod +x build/calibre.AppDir/AppRun

          mkdir -p build/calibre.AppDir/usr/bin/
          cd build/calibre.AppDir/usr/bin/
          curl -o - https://download.calibre-ebook.com/$version/calibre-$version-x86_64.txz | tar -xJf -

          pwd
          ls -lah
          cd ../../../../
          pwd
          ls -lah

          cp build/calibre.AppDir/usr/bin/resources/content-server/calibre.png build/calibre.AppDir
          cp README.md build/calibre.AppDir

      - name: Get appimagetool
        run: |
          set -x
          wget https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Make AppImage
        run:  |
          set -x
          ./appimagetool-x86_64.AppImage build/calibre.AppDir

      - name: List files and rename AppImage
        run: |
          set -x
          pwd
          ls -lah
          version=$(grep -o "Calibre:.*" README.md | cut -d ' ' -f2)
          echo "Calibre version: $version"

          mv Calibre-x86_64.AppImage "Calibre-$version-x86_64.AppImage"
          md5sum "Calibre-$version-x86_64.AppImage" > "Calibre-$version-x86_64.AppImage.md5"
          ls -lah

      - name: Create Release
        id: create_release
        uses: actions/create-release@master # Use master version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - uses: xresloader/upload-to-github-release@master # Use master version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "Calibre*.AppImage; Calibre*.md5"
          release_id: ${{ steps.create_release.outputs.id }}
          verbose: true
